const KEY="ssv_catalog_v1",SET="ssv_settings_v1",PASS="sriSai@2026";
const seed=[
{id:1,name:"Royal Banarasi",category:"Sarees",price:5499,newArrival:true,bestSeller:true,image:"assets/saree-1.svg"},
{id:2,name:"Rose Silk",category:"Sarees",price:4299,newArrival:true,bestSeller:false,image:"assets/saree-2.svg"},
{id:3,name:"Classic Kanchi",category:"Sarees",price:6999,newArrival:false,bestSeller:true,image:"assets/saree-3.svg"},
{id:4,name:"Festive Draped Dress",category:"Dresses",price:2899,newArrival:true,bestSeller:true,image:"assets/dress-1.svg"},
{id:5,name:"Ivory Occasion Dress",category:"Dresses",price:3499,newArrival:true,bestSeller:false,image:"assets/dress-2.svg"},
{id:6,name:"Maroon Anarkali",category:"Dresses",price:4599,newArrival:false,bestSeller:true,image:"assets/dress-3.svg"},
{id:7,name:"Temple Border Saree",category:"Sarees",price:3799,newArrival:false,bestSeller:false,image:"assets/saree-4.svg"},
{id:8,name:"Everyday Printed Dress",category:"Dresses",price:1899,newArrival:true,bestSeller:false,image:"assets/dress-4.svg"}];
var products=JSON.parse(localStorage.getItem(KEY)||"null")||seed;
var settings=JSON.parse(localStorage.getItem(SET)||"null")||{name:"SRI SAI VANI",whatsapp:"919999999999",instagram:"https://www.instagram.com/sri_sai_vani_collections/"};
var category="All";
function $(s){return document.querySelector(s)}function all(s){return document.querySelectorAll(s)}
function save(){localStorage.setItem(KEY,JSON.stringify(products));localStorage.setItem(SET,JSON.stringify(settings))}
function money(n){return "₹"+Number(n).toLocaleString("en-IN")}
function wa(p){return "https://wa.me/"+settings.whatsapp+"?text="+encodeURIComponent("Hi Sri Sai Vani, I am interested in "+p.name+" ("+money(p.price)+"). Is it available?")}
function renderTabs(){var cats=["All","Sarees","Dresses"];$("#tabs").innerHTML=cats.map(function(c){return '<button class="'+(category===c?"active":"")+'" data-tab="'+c+'">'+c.toUpperCase()+"</button>"}).join("")}
function render(){renderTabs();var q=$("#search").value.trim().toLowerCase(),pf=$("#price").value;var list=products.filter(function(p){return(category==="All"||p.category===category)&&(!q||p.name.toLowerCase().includes(q)||p.category.toLowerCase().includes(q))}).sort(function(a,b){return (Number(b.newArrival&&b.bestSeller)-Number(a.newArrival&&a.bestSeller))||(Number(b.newArrival)-Number(a.newArrival))||(Number(b.bestSeller)-Number(a.bestSeller))}).filter(function(p){if(!pf)return true;if(pf==="0-2000")return p.price<2000;if(pf==="2000-4000")return p.price>=2000&&p.price<4000;if(pf==="4000-7000")return p.price>=4000&&p.price<7000;return p.price>=7000});
$("#products").innerHTML=list.map(function(p){return '<article class="product-card"><div class="product-image"><img src="'+p.image+'" alt="'+p.name+'" onerror="this.style.display=\'none\'"><div class="badges">'+(p.newArrival?'<span class="badge new">NEW ARRIVAL</span>':"")+(p.bestSeller?'<span class="badge best">BEST SELLER</span>':"")+'</div></div><div class="product-info"><h3>'+p.name+'</h3><span class="meta">'+p.category+'</span><div class="price-line"><span class="price">'+money(p.price)+'</span><a class="wa-mini" href="'+wa(p)+'" target="_blank" rel="noopener">↗</a></div></div></article>'}).join("");
$("#empty").classList.toggle("hidden",!list.length)}
function form(p){p=p||{};return '<div class="admin-row"><input id="fName" placeholder="Product name" value="'+(p.name||"")+'"><select id="fCat"><option '+(p.category==="Sarees"?"selected":"")+' >Sarees</option><option '+(p.category==="Dresses"?"selected":"")+'>Dresses</option></select></div><div class="admin-row"><input id="fPrice" type="number" placeholder="Price" value="'+(p.price||"")+'"><input id="fImage" placeholder="Image path or URL" value="'+(p.image||"")+'"></div><label><input id="fNew" type="checkbox" '+(p.newArrival?"checked":"")+'> New arrival</label> <label><input id="fBest" type="checkbox" '+(p.bestSeller?"checked":"")+'> Best seller</label><br><br><button class="btn dark" id="saveItem">SAVE ITEM</button>'+(p.id?' <button class="danger" id="deleteItem">DELETE</button>':"")}
function showView(view){var body=$("#studioBody");if(view==="products"){body.innerHTML=products.map(function(p){return '<div class="admin-item"><div><strong>'+p.name+'</strong><br><small>'+p.category+' · '+money(p.price)+'</small></div><button class="danger edit" data-id="'+p.id+'">EDIT</button></div>'}).join("")}else if(view==="add"){body.innerHTML=form();$("#saveItem").onclick=function(){saveProduct(0)}}else{body.innerHTML='<p>Shop name</p><input id="setName" value="'+settings.name+'"><p>WhatsApp number</p><input id="setWa" value="'+settings.whatsapp+'"><p>Instagram URL</p><input id="setIg" value="'+settings.instagram+'"><button class="btn dark" id="saveSettings">SAVE SETTINGS</button>'}}
function edit(id){var p=products.find(function(x){return x.id===id});$("#studioBody").innerHTML=form(p);$("#saveItem").onclick=function(){saveProduct(id)};$("#deleteItem").onclick=function(){if(confirm("Delete this item?")){products=products.filter(function(x){return x.id!==id});save();render();showView("products")}}}
function saveProduct(id){var p={id:id||Date.now(),name:$("#fName").value.trim(),category:$("#fCat").value,price:Number($("#fPrice").value),image:$("#fImage").value.trim(),newArrival:$("#fNew").checked,bestSeller:$("#fBest").checked};if(!p.name||!p.price||!p.image){alert("Please fill product name, price and image.");return}if(id)products=products.map(function(x){return x.id===id?p:x});else products.unshift(p);save();render();showView("products")}
function apply(){document.querySelectorAll(".brand b").forEach(function(x){x.textContent=settings.name});$("#waMain").href="https://wa.me/"+settings.whatsapp+"?text="+encodeURIComponent("Hi Sri Sai Vani, I would like to know about your collection.");$("#instagram").href=settings.instagram}
$("#menu").onclick=function(){$("#nav").classList.toggle("open")};if($("#adminOpen"))$("#adminOpen").onclick=function(){$("#admin").classList.remove("hidden")};if($("#adminClose"))$("#adminClose").onclick=function(){$("#admin").classList.add("hidden")};
$("#loginBtn").onclick=function(){if($("#password").value===PASS){$("#login").classList.add("hidden");$("#studio").classList.remove("hidden");showView("products")}else $("#loginMsg").textContent="Incorrect password."};
all("[data-view]").forEach(function(b){b.onclick=function(){showView(b.dataset.view)}});
document.addEventListener("click",function(e){var tab=e.target.closest("[data-tab]");if(tab){category=tab.dataset.tab;render()}var cat=e.target.closest("[data-cat]");if(cat){category=cat.dataset.cat;$("#nav").classList.remove("open");render()}var editBtn=e.target.closest(".edit");if(editBtn)edit(Number(editBtn.dataset.id));if(e.target.id==="saveSettings"){settings.name=$("#setName").value.trim()||"SRI SAI VANI";settings.whatsapp=$("#setWa").value.replace(/\D/g,"");settings.instagram=$("#setIg").value.trim();save();apply();showView("products")}});
$("#search").oninput=render;$("#price").onchange=render;apply();render();